### ISSUE TITLE
Can't find package @mapbox/mapbox-gl-geocoder@^4.4.0 on win32 platform.

### ISSUE THREAD

**Issue by HanwGeek** [yeliudev/geoviewer#2]
× Install fail! Error: [@mapbox/mapbox-gl-geocoder@^4.4.0] Can't find package @mapbox/mapbox-gl-geocoder@^4.4.0
Error: [@mapbox/mapbox-gl-geocoder@^4.4.0] Can't find package @mapbox/mapbox-gl-geocoder@^4.4.0
    at resolve (C:\Users\Wang\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\download\npm.js:78:11)
    at resolve.next (<anonymous>)
    at onFulfilled (C:\Users\Wang\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

I modify the version of geocoder in package.json file from "^4.4.0" to "^4.0.0" and it worked.
-----------------------------------------------------------------------------------------------------------
Now there comes bugs.

**Comment by yeliudev** [comment]
Thx so much! `@mapbox/mapbox-gl-geocoder@^4.4.0` works on macOS, and the package can be found at https://www.npmjs.com/package/@mapbox/mapbox-gl-geocoder, maybe this is a bug on win32 platform.
